version: "3"
services:
  db:
    image: postgres
    container_name: postgres_pawpal
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro